name: CI

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install uv
        run: astral-sh/setup-uv@v5
      
      - name: Install the project
        run: uv sync --all-extras

      - name: List directory contents
        run: ls -la

      - name: Run tests
        run: uv run pytest -v testes.py